swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.2
host: http://localhost:8080
basePath: /api
schemes:
  - http
paths:
  /user/{name}:
    post:
      summary: Returns new user.
      description: Optional extended description in Markdown. 1131
      produces:
        - application/json
      responses:
        200:
          description: OK